on: [pull_request_target]
name: Auto-Merge Bot
jobs:
  await_ci:
    runs-on: ubuntu-latest
    name: Await Travis CI Success
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: await-ci
        uses: alita-moore/EIP-Bot@372a671f9eb63df50b1659ccfbe94594c7bbfc29 # await-ci-pass
        id: await-ci
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }} 
  auto_merge_bot:
    runs-on: ubuntu-latest
    needs: [await_ci]
    name: EIP Auto-Merge Bot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: auto-merge-bot
        uses: alita-moore/EIP-Bot@1b25b8093d7c0acfbe45a534a150097dbef75b84 # master
        id: auto-merge-bot
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }} 
