on: 
  pull_request_target:
  pull_request_review:
    types: [submitted]
name: Auto-Merge Bot
jobs:
  await_ci:
    runs-on: ubuntu-latest
    name: Await Travis CI Success
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: await-ci
        uses: alita-moore/EIP-Bot@372a671f9eb63df50b1659ccfbe94594c7bbfc29
        id: await-ci
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }} 
  rerun_bot_on_review:
    if: ${{ github.event_name == 'pull_request_review' }}
    runs-on: ubuntu-latest
    needs: [await_ci]
    name: Rerun Bot on Review
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Re-run pull_request_target bot run on pull_request_review
        uses: alita-moore/EIP-Bot@724e1eeaca560e4cf06dcc3f2345e94e7541fad9
        id: rerun-pull-request-target-on-review
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }}
  auto_merge_bot:
    if: ${{ github.event_name == 'pull_request_target' }}
    runs-on: ubuntu-latest
    needs: [await_ci, rerun_bot_on_review]
    name: EIP Auto-Merge Bot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: auto-merge-bot
        
        uses: alita-moore/EIP-Bot@bbc378a87486973e55d7073b09e0d8e6088326b4
        id: auto-merge-bot
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }} 
